INSERT INTO questions (title, body, user_id)
VALUES ('How can you add a delete button efficiently by PHP?',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis volutpat erat, in feugiat est sollicitudin eu. In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    1);

INSERT INTO questions (title, body, user_id)
VALUES ('To read SO effieciently ',
    'In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    1);

INSERT INTO questions (title, body, user_id)
VALUES ('How can you add a ring system like in Linux kernel to my website?',
    'Hienoa! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis volutpat erat, in feugiat est sollicitudin eu. In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    2);

INSERT INTO questions (title, body, user_id)
VALUES ('How can you draw a turtle by Logo?',
    'Donec iaculis volutpat erat, in feugiat est sollicitudin eu. In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    2);


INSERT INTO questions (title, body, user_id)
VALUES ('How can you add a rootkit to my website?',
    'Quisque neque metus, faucibus euismod luctus sed, tempor nec tellus. Fusce rutrum hendrerit orci et mattis. Proin metus nisi, scelerisque quis sagittis nec, rutrum eget sem. Nulla laoreet libero in leo mollis ac gravida justo bibendum. Sed vulputate lectus a lectus pulvinar vulputate. Curabitur imperdiet pellentesque nulla, ut tincidunt dui tincidunt at. Donec at adipiscing orci. Integer et hendrerit elit. Vestibulum condimentum lacus at tellus tincidunt porta. Pellentesque dapibus congue neque, sed elementum leo laoreet ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec dui sapien, pellentesque eget eleifend sed, aliquam non risus. Maecenas ut ligula purus. Vestibulum tempor neque eu ligula mollis vitae tincidunt dui feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non porta dolor.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis volutpat erat, in feugiat est sollicitudin eu. In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    3);

INSERT INTO questions (title, body, user_id)
VALUES ('To answer questions efficiently',
    'Fusce rutrum hendrerit orci et mattis. Proin metus nisi, scelerisque quis sagittis nec, rutrum eget sem. Nulla laoreet libero in leo mollis ac gravida justo bibendum. Sed vulputate lectus a lectus pulvinar vulputate. Curabitur imperdiet pellentesque nulla, ut tincidunt dui tincidunt at. Donec at adipiscing orci. Integer et hendrerit elit. Vestibulum condimentum lacus at tellus tincidunt porta. Pellentesque dapibus congue neque, sed elementum leo laoreet ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec dui sapien, pellentesque eget eleifend sed, aliquam non risus. Maecenas ut ligula purus. Vestibulum tempor neque eu ligula mollis vitae tincidunt dui feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non porta dolor.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis volutpat erat, in feugiat est sollicitudin eu. In odio nibh, varius sit amet fringilla nec, commodo eget libero. Suspendisse feugiat sem id justo eleifend quis tempus orci mollis. Nulla ornare nulla lobortis mi egestas viverra. Suspendisse sit amet fringilla nunc. Donec ac feugiat odio. Mauris vel purus velit, ac facilisis orci. Fusce purus dolor, interdum quis molestie sit amet, malesuada in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique rutrum justo nec tincidunt. Donec aliquam eros et dolor consectetur tincidunt. Phasellus cursus hendrerit est, vitae lacinia enim consequat eu. Vestibulum ac felis diam. Sed sit amet lectus vitae urna consequat pulvinar vitae ac dui.',
    3);
