<?php
$iso3cc   = $_SESSION['iso3cc'];
$thisone  = "sel".strtolower($iso3cc);
$$thisone = "selected";
?>
<select id='countrySelect' name="country" size="1" class="state" onchange='updateState(this.id)'>
<option <?php echo $selusa; ?> value="USA">United States</option>
<option <?php echo $selcan; ?> value="CAN">Canada</option>
<option <?php echo $selafg; ?> value="AFG">Afghanistan</option>
<option <?php echo $selalb; ?> value="ALB">Albania</option>
<option <?php echo $seldza; ?> value="DZA">Algeria</option>
<option <?php echo $selasm; ?> value="ASM">American Samoa</option>
<option <?php echo $seland; ?> value="AND">Andorra</option>
<option <?php echo $selago; ?> value="AGO">Angola</option>
<option <?php echo $selaia; ?> value="AIA">Anguilla</option>
<option <?php echo $selata; ?> value="ATA">Antarctica</option>
<option <?php echo $selatg; ?> value="ATG">Antigua and Barbuda</option>
<option <?php echo $selarg; ?> value="ARG">Argentina</option>
<option <?php echo $selarm; ?> value="ARM">Armenia</option>
<option <?php echo $selabw; ?> value="ABW">Aruba</option>
<option <?php echo $selaus; ?> value="AUS">Australia</option>
<option <?php echo $selaut; ?> value="AUT">Austria</option>
<option <?php echo $selaze; ?> value="AZE">Azerbaijan</option>
<option <?php echo $selbhs; ?> value="BHS">Bahamas</option>
<option <?php echo $selbhr; ?> value="BHR">Bahrain</option>
<option <?php echo $selbgd; ?> value="BGD">Bangladesh</option>
<option <?php echo $selbrb; ?> value="BRB">Barbados</option>
<option <?php echo $selblr; ?> value="BLR">Belarus</option>
<option <?php echo $selbel; ?> value="BEL">Belgium</option>
<option <?php echo $selblz; ?> value="BLZ">Belize</option>
<option <?php echo $selben; ?> value="BEN">Benin</option>
<option <?php echo $selbmu; ?> value="BMU">Bermuda</option>
<option <?php echo $selbtn; ?> value="BTN">Bhutan</option>
<option <?php echo $selbol; ?> value="BOL">Bolivia</option>
<option <?php echo $selbih; ?> value="BIH">Bosnia and Herzegowina</option>
<option <?php echo $selbwa; ?> value="BWA">Botswana</option>
<option <?php echo $selbvt; ?> value="BVT">Bouvet Island</option>
<option <?php echo $selbra; ?> value="BRA">Brazil</option>
<option <?php echo $seliot; ?> value="IOT">British Indian Ocean Terr.</option>
<option <?php echo $selbrn; ?> value="BRN">Brunei Darussalam</option>
<option <?php echo $selbgr; ?> value="BGR">Bulgaria</option>
<option <?php echo $selbfa; ?> value="BFA">Burkina Faso</option>
<option <?php echo $selbdi; ?> value="BDI">Burundi</option>
<option <?php echo $selkhm; ?> value="KHM">Cambodia</option>
<option <?php echo $selcmr; ?> value="CMR">Cameroon</option>
<option <?php echo $selcpv; ?> value="CPV">Cape Verde</option>
<option <?php echo $selcym; ?> value="CYM">Cayman Islands</option>
<option <?php echo $selcaf; ?> value="CAF">Central African Republic</option>
<option <?php echo $seltcd; ?> value="TCD">Chad</option>
<option <?php echo $selchl; ?> value="CHL">Chile</option>
<option <?php echo $selchn; ?> value="CHN">China</option>
<option <?php echo $selcxr; ?> value="CXR">Christmas Island</option>
<option <?php echo $selcck; ?> value="CCK">Cocos (Keeling) Islands</option>
<option <?php echo $selcol; ?> value="COL">Colombia</option>
<option <?php echo $selcom; ?> value="COM">Comoros</option>
<option <?php echo $selcog; ?> value="COG">Congo</option>
<option <?php echo $selcok; ?> value="COK">Cook Islands</option>
<option <?php echo $selcri; ?> value="CRI">Costa Rica</option>
<option <?php echo $selciv; ?> value="CIV">Cote d&#amp;Ivoire</option>
<option <?php echo $selhrv; ?> value="HRV">Croatia (Hrvatska)</option>
<option <?php echo $selcub; ?> value="CUB">Cuba</option>
<option <?php echo $selcyp; ?> value="CYP">Cyprus</option>
<option <?php echo $selcze; ?> value="CZE">Czech Republic</option>
<option <?php echo $seldnk; ?> value="DNK">Denmark</option>
<option <?php echo $seldji; ?> value="DJI">Djibouti</option>
<option <?php echo $seldma; ?> value="DMA">Dominica</option>
<option <?php echo $seldom; ?> value="DOM">Dominican Republic</option>
<option <?php echo $seltmp; ?> value="TMP">East Timor</option>
<option <?php echo $selecu; ?> value="ECU">Ecuador</option>
<option <?php echo $selegy; ?> value="EGY">Egypt</option>
<option <?php echo $selslv; ?> value="SLV">El Salvador</option>
<option <?php echo $selgnq; ?> value="GNQ">Equatorial Guinea</option>
<option <?php echo $seleri; ?> value="ERI">Eritrea</option>
<option <?php echo $selest; ?> value="EST">Estonia</option>
<option <?php echo $seleth; ?> value="ETH">Ethiopia</option>
<option <?php echo $selflk; ?> value="FLK">Falkland Islands/Malvinas</option>
<option <?php echo $selfro; ?> value="FRO">Faroe Islands</option>
<option <?php echo $selfji; ?> value="FJI">Fiji</option>
<option <?php echo $selfin; ?> value="FIN">Finland</option>
<option <?php echo $selfra; ?> value="FRA">France</option>
<option <?php echo $selfxx; ?> value="FXX">France, Metropolitan</option>
<option <?php echo $selguf; ?> value="GUF">French Guiana</option>
<option <?php echo $selpyf; ?> value="PYF">French Polynesia</option>
<option <?php echo $selatf; ?> value="ATF">French Southern Terr.</option>
<option <?php echo $selgab; ?> value="GAB">Gabon</option>
<option <?php echo $selgmb; ?> value="GMB">Gambia</option>
<option <?php echo $selgeo; ?> value="GEO">Georgia</option>
<option <?php echo $seldeu; ?> value="DEU">Germany</option>
<option <?php echo $selgha; ?> value="GHA">Ghana</option>
<option <?php echo $selgib; ?> value="GIB">Gibraltar</option>
<option <?php echo $selgrc; ?> value="GRC">Greece</option>
<option <?php echo $selgrl; ?> value="GRL">Greenland</option>
<option <?php echo $selgrd; ?> value="GRD">Grenada</option>
<option <?php echo $selglp; ?> value="GLP">Guadeloupe</option>
<option <?php echo $selgum; ?> value="GUM">Guam</option>
<option <?php echo $selgtm; ?> value="GTM">Guatemala</option>
<option <?php echo $selgim; ?> value="GIN">Guinea</option>
<option <?php echo $selgnb; ?> value="GNB">Guinea-Bissau</option>
<option <?php echo $selguy; ?> value="GUY">Guyana</option>
<option <?php echo $selhti; ?> value="HTI">Haiti</option>
<option <?php echo $selhmd; ?> value="HMD">Heard & McDonald Is.</option>
<option <?php echo $selhnd; ?> value="HND">Honduras</option>
<option <?php echo $selhkg; ?> value="HKG">Hong Kong</option>
<option <?php echo $selhun; ?> value="HUN">Hungary</option>
<option <?php echo $selisl; ?> value="ISL">Iceland</option>
<option <?php echo $selind; ?> value="IND">India</option>
<option <?php echo $selidn; ?> value="IDN">Indonesia</option>
<option <?php echo $selirn; ?> value="IRN">Iran</option>
<option <?php echo $selirq; ?> value="IRQ">Iraq</option>
<option <?php echo $selirl; ?> value="IRL">Ireland</option>
<option <?php echo $selisr; ?> value="ISR">Israel</option>
<option <?php echo $selita; ?> value="ITA">Italy</option>
<option <?php echo $seljam; ?> value="JAM">Jamaica</option>
<option <?php echo $seljpn; ?> value="JPN">Japan</option>
<option <?php echo $seljor; ?> value="JOR">Jordan</option>
<option <?php echo $selkaz; ?> value="KAZ">Kazakhstan</option>
<option <?php echo $selken; ?> value="KEN">Kenya</option>
<option <?php echo $selkir; ?> value="KIR">Kiribati</option>
<option <?php echo $selprk; ?> value="PRK">Korea, North</option>
<option <?php echo $selkor; ?> value="KOR">Korea, South</option>
<option <?php echo $selkwt; ?> value="KWT">Kuwait</option>
<option <?php echo $selkgz; ?> value="KGZ">Kyrgyzstan</option>
<option <?php echo $sellao; ?> value="LAO">Lao People&#039;s Dem. Rep.</option>
<option <?php echo $sellva; ?> value="LVA">Latvia</option>
<option <?php echo $sellbn; ?> value="LBN">Lebanon</option>
<option <?php echo $sellso; ?> value="LSO">Lesotho</option>
<option <?php echo $sellbr; ?> value="LBR">Liberia</option>
<option <?php echo $sellby; ?> value="LBY">Libyan Arab Jamahiriya</option>
<option <?php echo $sellie; ?> value="LIE">Liechtenstein</option>
<option <?php echo $selltu; ?> value="LTU">Lithuania</option>
<option <?php echo $sellux; ?> value="LUX">Luxembourg</option>
<option <?php echo $selmac; ?> value="MAC">Macau</option>
<option <?php echo $selmkd; ?> value="MKD">Macedonia</option>
<option <?php echo $selmdg; ?> value="MDG">Madagascar</option>
<option <?php echo $selmwi; ?> value="MWI">Malawi</option>
<option <?php echo $selmsy; ?> value="MYS">Malaysia</option>
<option <?php echo $selmdv; ?> value="MDV">Maldives</option>
<option <?php echo $selmli; ?> value="MLI">Mali</option>
<option <?php echo $selmlt; ?> value="MLT">Malta</option>
<option <?php echo $selmhl; ?> value="MHL">Marshall Islands</option>
<option <?php echo $selmtq; ?> value="MTQ">Martinique</option>
<option <?php echo $selmrt; ?> value="MRT">Mauritania</option>
<option <?php echo $selmus; ?> value="MUS">Mauritius</option>
<option <?php echo $selmyt; ?> value="MYT">Mayotte</option>
<option <?php echo $selmex; ?> value="MEX">Mexico</option>
<option <?php echo $selfsm; ?> value="FSM">Micronesia</option>
<option <?php echo $selmda; ?> value="MDA">Moldova</option>
<option <?php echo $selmco; ?> value="MCO">Monaco</option>
<option <?php echo $selmng; ?> value="MNG">Mongolia</option>
<option <?php echo $selmsr; ?> value="MSR">Montserrat</option>
<option <?php echo $selmar; ?> value="MAR">Morocco</option>
<option <?php echo $selmoz; ?> value="MOZ">Mozambique</option>
<option <?php echo $selmmr; ?> value="MMR">Myanmar</option>
<option <?php echo $selnam; ?> value="NAM">Namibia</option>
<option <?php echo $selnru; ?> value="NRU">Nauru</option>
<option <?php echo $selnpl; ?> value="NPL">Nepal</option>
<option <?php echo $selnld; ?> value="NLD">Netherlands</option>
<option <?php echo $selant; ?> value="ANT">Netherlands Antilles</option>
<option <?php echo $selncl; ?> value="NCL">New Caledonia</option>
<option <?php echo $selnzl; ?> value="NZL">New Zealand</option>
<option <?php echo $selnic; ?> value="NIC">Nicaragua</option>
<option <?php echo $selner; ?> value="NER">Niger</option>
<option <?php echo $selnga; ?> value="NGA">Nigeria</option>
<option <?php echo $selniu; ?> value="NIU">Niue</option>
<option <?php echo $selnfk; ?> value="NFK">Norfolk Island</option>
<option <?php echo $selmnp; ?> value="MNP">Northern Mariana Is.</option>
<option <?php echo $selnor; ?> value="NOR">Norway</option>
<option <?php echo $selomn; ?> value="OMN">Oman</option>
<option <?php echo $selpak; ?> value="PAK">Pakistan</option>
<option <?php echo $selplw; ?> value="PLW">Palau</option>
<option <?php echo $selpan; ?> value="PAN">Panama</option>
<option <?php echo $selpng; ?> value="PNG">Papua New Guinea</option>
<option <?php echo $selpry; ?> value="PRY">Paraguay</option>
<option <?php echo $selper; ?> value="PER">Peru</option>
<option <?php echo $selphl; ?> value="PHL">Philippines</option>
<option <?php echo $selpcn; ?> value="PCN">Pitcairn</option>
<option <?php echo $selpol; ?> value="POL">Poland</option>
<option <?php echo $selprt; ?> value="PRT">Portugal</option>
<option <?php echo $selpri; ?> value="PRI">Puerto Rico</option>
<option <?php echo $selqat; ?> value="QAT">Qatar</option>
<option <?php echo $selreu; ?> value="REU">Reunion</option>
<option <?php echo $selrom; ?> value="ROM">Romania</option>
<option <?php echo $selrus; ?> value="RUS">Russian Federation</option>
<option <?php echo $selrwa; ?> value="RWA">Rwanda</option>
<option <?php echo $selkna; ?> value="KNA">Saint Kitts and Nevis</option>
<option <?php echo $sellca; ?> value="LCA">Saint Lucia</option>
<option <?php echo $selvct; ?> value="VCT">St. Vincent & Grenadines</option>
<option <?php echo $selwsm; ?> value="WSM">Samoa</option>
<option <?php echo $selsmr; ?> value="SMR">San Marino</option>
<option <?php echo $selstp; ?> value="STP">Sao Tome & Principe</option>
<option <?php echo $selsau; ?> value="SAU">Saudi Arabia</option>
<option <?php echo $selsen; ?> value="SEN">Senegal</option>
<option <?php echo $selsyc; ?> value="SYC">Seychelles</option>
<option <?php echo $selsle; ?> value="SLE">Sierra Leone</option>
<option <?php echo $selsgp; ?> value="SGP">Singapore</option>
<option <?php echo $selsvk; ?> value="SVK">Slovakia (Slovak Republic)</option>
<option <?php echo $selsvn; ?> value="SVN">Slovenia</option>
<option <?php echo $selslb; ?> value="SLB">Solomon Islands</option>
<option <?php echo $selsom; ?> value="SOM">Somalia</option>
<option <?php echo $selzaf; ?> value="ZAF">South Africa</option>
<option <?php echo $selsgs; ?> value="SGS">S.Georgia & S.Sandwich Is.</option>
<option <?php echo $selesp; ?> value="ESP">Spain</option>
<option <?php echo $sellka; ?> value="LKA">Sri Lanka</option>
<option <?php echo $selshn; ?> value="SHN">St. Helena</option>
<option <?php echo $selspm; ?> value="SPM">St. Pierre & Miquelon</option>
<option <?php echo $selsdn; ?> value="SDN">Sudan</option>
<option <?php echo $selsur; ?> value="SUR">Suriname</option>
<option <?php echo $selsjm; ?> value="SJM">Svalbard & Jan Mayen Is.</option>
<option <?php echo $selswz; ?> value="SWZ">Swaziland</option>
<option <?php echo $selswe; ?> value="SWE">Sweden</option>
<option <?php echo $selche; ?> value="CHE">Switzerland</option>
<option <?php echo $selsyr; ?> value="SYR">Syrian Arab Republic</option>
<option <?php echo $seltwn; ?> value="TWN">Taiwan</option>
<option <?php echo $seltjk; ?> value="TJK">Tajikistan</option>
<option <?php echo $seltza; ?> value="TZA">Tanzania</option>
<option <?php echo $seltha; ?> value="THA">Thailand</option>
<option <?php echo $seltgo; ?> value="TGO">Togo</option>
<option <?php echo $seltkl; ?> value="TKL">Tokelau</option>
<option <?php echo $selton; ?> value="TON">Tonga</option>
<option <?php echo $seltto; ?> value="TTO">Trinidad and Tobago</option>
<option <?php echo $seltun; ?> value="TUN">Tunisia</option>
<option <?php echo $seltur; ?> value="TUR">Turkey</option>
<option <?php echo $seltkm; ?> value="TKM">Turkmenistan</option>
<option <?php echo $seltca; ?> value="TCA">Turks & Caicos Islands</option>
<option <?php echo $seltuv; ?> value="TUV">Tuvalu</option>
<option <?php echo $seluga; ?> value="UGA">Uganda</option>
<option <?php echo $selukr; ?> value="UKR">Ukraine</option>
<option <?php echo $selare; ?> value="ARE">United Arab Emirates</option>
<option <?php echo $selgbr; ?> value="GBR">United Kingdom</option>
<option <?php echo $selumi; ?> value="UMI">U.S. Minor Outlying Is.</option>
<option <?php echo $selury; ?> value="URY">Uruguay</option>
<option <?php echo $seluzb; ?> value="UZB">Uzbekistan</option>
<option <?php echo $selvut; ?> value="VUT">Vanuatu</option>
<option <?php echo $selvat; ?> value="VAT">Vatican (Holy See)</option>
<option <?php echo $selven; ?> value="VEN">Venezuela</option>
<option <?php echo $selvnm; ?> value="VNM">Viet Nam</option>
<option <?php echo $selvgb; ?> value="VGB">Virgin Islands (British)</option>
<option <?php echo $selvir; ?> value="VIR">Virgin Islands (U.S.)</option>
<option <?php echo $selwlf; ?> value="WLF">Wallis & Futuna Is.</option>
<option <?php echo $selesh; ?> value="ESH">Western Sahara</option>
<option <?php echo $selyem; ?> value="YEM">Yemen</option>
<option <?php echo $selyug; ?> value="YUG">Yugoslavia</option>
<option <?php echo $selzar; ?> value="ZAR">Zaire</option>
<option <?php echo $selzmb; ?> value="ZMB">Zambia</option>
<option <?php echo $selzwe; ?> value="ZWE">Zimbabwe</option>
</select>
